schema_version = "1.0.0"
id = "Planetka"
version = "1.0.0"
name = "Planetka"
tagline = "Cinematic Earth Visualisation System"
maintainer = "Tomas Griger <info@planetka.io>"
type = "add-on"
blender_version_min = "4.5.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://www.planetka.io"
